/// Flutter icons MainIcon
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MainIcon
///      fonts:
///       - asset: fonts/MainIcon.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MainIcon {
  MainIcon._();

  static const _kFontFam = 'MainIcon';

  static const IconData home = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData shop = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData shopping_cart = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData hunt_list = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData notification = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData add = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData profile = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData back = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData forward = IconData(0xe80a, fontFamily: _kFontFam);
}
